// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaaghajrihzkfiwrpysm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhYWdoYWpyaWh6a2Zpd3JweXNtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTQ1MjksImV4cCI6MjA2NzQzMDUyOX0.N-PYEl_vABiNJaEUZaej3YggtomFS6h935sdtWDfpsY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});